

[snowflake]
SNOWFLAKE_ACCOUNT = 
SNOWFLAKE_HOST = "chswrge-ya35642.snowflakecomputing.com"
SNOWFLAKE_USER = 
SNOWFLAKE_PASSWORD = 
SNOWFLAKE_WAREHOUSE = "COMPUTE_WH"
SNOWFLAKE_DATABASE = "INSURANCE"
SNOWFLAKE_ROLE = "ACCOUNTADMIN"
